-- dealing-with-contention-v2 (enhanced): idempotency ledger for inbound payment webhooks.
-- The UNIQUE constraint on payment_reference is the exactly-once mechanism: concurrent
-- duplicate webhooks race to INSERT and exactly one wins; the losers see the violation and
-- must treat the event as already processed.
CREATE TABLE payment_event
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_reference VARCHAR(200) NOT NULL,
    reservation_id    BIGINT       NOT NULL,
    outcome           VARCHAR(50)  NOT NULL,
    processed_at      TIMESTAMP    NOT NULL,
    CONSTRAINT uq_payment_event_reference UNIQUE (payment_reference)
);
